server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5dGhhdGlzYXRsZWFzdDUxMmJpdHNsb25nZm9ySFM1MTJhbGdvcml0aG00"
  expirationMs: 86400000

